variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test

build_project:
  stage: test
  variables:
    APPKID_LOCAL_BUILD: "1"
  script:
    - rm -rf .build
    - swift test -v --build-path .build
