variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

build_project:
  stage: build
  variables:
    APPKID_LOCAL_BUILD: "1"
  script:
    - rm -rf .build
    - swift build --product AppKidDemo -v --build-path .build/AppKidDemo
