#
#  .spi.yml
#  AppKid
#  
#  Created by Serhii Mumriak on 04.04.2023
#

version: 1
builder:
  configs:
  - platform: linux
    swift_version:
    - '5.8'
    - '5.9'
    image: registry.gitlab.com/finestructure/spi-images:AppKid-5.8-latest
    documentation_targets:
    - AppKid
    - CairoGraphics
    - ContentAnimation
    - SimpleGLM
    - SwiftXlib
    - SwiftyGLib
    - TinyFoundation
    - Volcano
