name: 'Build AppKidDemo'
on: push

jobs:
  build_project:
    runs-on: [self-hosted, ubuntu]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Clean Build Directory
      run: rm -rf .build

    - name: Build
      run: swift build --product AppKidDemo -v --build-path .build/AppKidDemo