#
#  push-docker-toolchain.yml
#  AppKid
#  
#  Created by Serhii Mumriak on 02.02.2023
#

name: 'Test Everything'
on: push

jobs:
  test_everything:
    runs-on: [self-hosted, ubuntu]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Clean Build Directory
      run: rm -rf .build

    - name: Test
      run: swift test -v  --build-path .build
